### ISSUE TITLE
Any updates for GPT4 API

### ISSUE THREAD

**Issue by erbill** [borge12/simple-chat#7]
I've just received GPT4 API access, and wondering if you're planning to update simple-chat to work with GPT4 ? What are your thoughts on this?

**Comment by awiggins12** [comment]
Just pushed a change that has a drop down for a model within the settings.  By default it will use 3.5.  

Weirdly when using GPT4 I get different responses than when using OpenAPI's UI.  Asking if it is Chat GPT4 results in it denying 4 exists on simple-chat, but their UI will tell me it does exist.  

But, I did confirm that it's working by examining the response and the response confirms that it's GPT4.  It seems to be significantly slower than 3.5 as well.
